mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sitebase.urls')),
]

# MEDIA_ROOTを公開する（アクセス可能にする）
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitebase/urls.py
from django.urls import path

from . import views

app_name = 'sitebase'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('news/', views.news, name='news'),
    path('news/<int:topic_id>/', views.newsdetail, name='newsdetail'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('contact/done', views.ContactDoneView.as_view(), name='contactdone'),
]

sitebase/models.py
from django.db import models


class Topic(models.Model):
    CATEGORY_CHOICES = (
                ('I', 'INFO'),
                ('S', 'SERVICE'),
                ('W', 'WORK'),
                ('T', 'TECH'),
            )
    release_day = models.DateField(verbose_name='発表日')
    category = models.CharField(
                verbose_name='カテゴリ',
                max_length=1,
                choices=CATEGORY_CHOICES
            )
    title = models.CharField(verbose_name='タイトル', max_length=128)
    content = models.TextField(verbose_name='本文', max_length=4096)
    photo = models.ImageField(
                verbose_name='イメージ',
                upload_to='tphotos',
                blank=True,
                null=True
            )
    link = models.URLField(
                verbose_name='関連リンク',
                blank=True,
                null=True
            )
    votes = models.IntegerField(verbose_name='いいね数', default=0)
    create_date = models.DateTimeField(verbose_name='登録日', auto_now=True)

    def __str__(self):
        return self.title

sitebase/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.core.mail import EmailMessage
from django.conf import settings


class ContactForm(forms.Form):
    phone_rg = RegexValidator(regex=r'^[0-9\-]+$')
    # message=("電話番号は数字と - のみで入力してください"))

    name = forms.CharField(label='お名前', max_length=200)

    email = forms.EmailField(label='メールアドレス', max_length=100)

    phone = forms.CharField(
            label='電  話',
            validators=[phone_rg],
            max_length=15)

    comment = forms.CharField(
            label='内  容',
            widget=forms.Textarea,
            max_length=800)

    def send_email(self):
        fdata = self.cleaned_data

        subject = 'ロングリブネットへのお問い合わせ'
        from_email = settings.FROM_EMAIL_ADDRESS
        to = [fdata['email']]
        ccs = [from_email]
        message = """
{name} 様

ロングリブネットにお問い合わせいただきまして
誠にありがとうございました。

以下のお問い合わせを承りました。
-------------------

◆ お名前
{name} 様

◆ メールアドレス
{email}

◆ 電話番号
{phone}

◆ お問い合わせ内容
{comment}

-------------------
当お問い合わせにつきましては、追ってロング
リブネットよりご連絡させていただきます。
何卒今しばらくお待ちください。

今後ともよろしくお願い申し上げます。

        """.format(**fdata)

        # Send EMail
        em = EmailMessage(subject, message, from_email, to, cc=[], bcc=ccs)
        em.send()

sitebase/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.core import paginator
from django.conf import settings
from django.urls import reverse_lazy

from .models import Topic
from .forms import ContactForm


class IndexView(generic.TemplateView):
    template_name = 'sitebase/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news_list'] = Topic.objects.order_by('-release_day')[:5]
        return context


def paginate_queryset(page, queryset, count):
    pgn = paginator.Paginator(queryset, count)
    try:
        page_obj = pgn.page(page)
    except paginator.PageNotAnInteger:
        print("pageNotAnInteger")
        page_obj = pgn.page(1)
    except paginator.EmptyPage:
        print("EmptyPage")
        page_obj = pgn.page(pgn.num_pages)
    return page_obj


def news(request):
    count = settings.NEWS_PAGE_ITEM_COUNT
    page = request.GET.get('page') or '1'
    topicsall = Topic.objects.order_by('-release_day')
    page_obj = paginate_queryset(page, topicsall, count)
    context = {'page_obj': page_obj}
    return render(request, 'sitebase/news.html', context)


def newsdetail(request, topic_id):
    page = request.GET.get('page')
    news = get_object_or_404(Topic, pk=topic_id)
    context = {'news': news, 'page': page}
    return render(request, 'sitebase/news_detail.html', context)


class ContactView(generic.FormView):
    form_class = ContactForm
    template_name = "sitebase/contact.html"
    success_url = reverse_lazy('sitebase:contactdone')

    def form_valid(self, form):
        ctx = {'form': form}
        if self.request.POST.get('next', '') == 'confirm':
            return render(self.request, 'sitebase/contact_confirm.html', ctx)
        elif self.request.POST.get('next', '') == 'back':
            return render(self.request, 'sitebase/contact.html', ctx)
        elif self.request.POST.get('next', '') == 'send':
            form.send_email()
            return super().form_valid(form)
        else:
            return redirect(reverse_lazy('sitebase:contact'))


class ContactDoneView(generic.TemplateView):
    template_name = "sitebase/contact_done.html"

sitebase/templates/sitebase/contact.html
{% extends "base.html" %}

{% block title %}ContactForm{% endblock title %}

{% block content %}

<section id="contact_form" class="center_block">
  <h1>お問い合せフォーム</h1>
  <div class ="cform">
    <h4>メールでのご連絡は以下のフォームをご利用ください</h4>
    <form method="post">
      {% csrf_token %}
      <p>
      {{ form.errors.name }}
      <label>
        <strong>{{ form.name.label }}</strong><br>{{ form.name }}
      </label>
      </p>
      <p>
      {{ form.errors.email }}
      <label>
        <strong>{{ form.email.label }}</strong><br>{{ form.email }}
      </label>
      </p>
      <p>
      {{ form.errors.phone }}
      <label>
        <strong>{{ form.phone.label }}</strong><br>{{ form.phone }}
      </label>
      </p>
      <p>
      {{ form.errors.comment }}
      <label>
        <strong>{{ form.comment.label }}</strong><br>{{ form.comment }}
      </label>
      </p>
      <button name="next" value="confirm" type="submit" class="cbutton">入力内容を確認する</button>
    </form>
  </div>
  <div>
    <p>
    <a class="button01" href="/#contact">戻る</a>
    <a class="button01" href="/">ホーム</a>
    </p>
  </div>

</section>

{% endblock %}

sitebase/templates/sitebase/contact_confirm.html
{% extends "base.html" %}

{% block title %}Confirm{% endblock title %}

{% block content %}

<section id="contact_confirm" class="center_block">
  <h1>お問い合せ内容の確認</h1>
  <div class ="contact_info">
    <h4>以下の内容でメールを送信しますがよろしいでしょうか？</h4>
    <hr>
    <p>
    <strong>{{ form.name.label }}</strong><br>{{ form.name.value }}
    </p>
    <p>
    <strong>{{ form.email.label }}</strong><br>{{ form.email.value }}
    </p>
    <p>
    <strong>{{ form.phone.label }}</strong><br>{{ form.phone.value }}
    </p>
    <p>
    <strong>{{ form.comment.label }}</strong><br>{{ form.comment.value  | linebreaksbr }}
    </p>
    <hr>
    <form action="{% url 'sitebase:contact' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
      {{ field.as_hidden }}
      {% endfor %}
      <button type="submit" name="next" value="back" class="cbutton">修正する</button>
      <button type="submit" name="next" value="send" class="cbutton">送信する</button>
    </form>
  </div>
</section>

{% endblock %}

sitebase/templates/sitebase/contact_done.html
{% extends "base.html" %}

{% block title %}ContactForm{% endblock title %}

{% block content %}


<section id="contact_done" class="center_block">
  <h1>お問い合せを受け付けました</h1>
  <div class="contact_info">
    <p>お問い合せいただきまして誠にありがとうございました。</p>
    <p>追って担当よりご連絡いたします。</p>
  </div>
  <div>
    <p>
    <a class="button01" href="/#contact">連絡先に戻る</a>
    <a class="button01" href="/">ホーム</a>
    </p>
  </div>
</section>

{% endblock %}

sitebase/templates/sitebase/index.html
{% extends "base.html" %}

{% block title %}ホーム{% endblock title %}

{% block content %}

{% load static %}

<section id="topimage">
  <div style="background-image: url('{% static 'images/top01.jpg' %}')">
    <h1>情報技術をチカラにしたい！<br>
      ロングリブネットがサポートいたします</h1>
  </div>
</section>

<section id="message">
  <h3 class="underline">Message</h3>
  <div class="content_block">
    <div class="pr_eyecatch" style="background-image: url('{% static 'images/message01.jpg' %}')">
      <h3>システムデザインとか IT 活用とか正直どうしてよいかよく解らないんですよ・・</h3>
    </div>
    <div class="pr_leader">
      <p>多くの方よりこのような悩みをご相談をいただいた気がします</p>
      <p>
      このような悩みを解決するには、その悩みに寄り添い適切な技術をご提供できることが第一です。<br/>
      一方で、お悩みをお持ちの方ご自身や組織自体にも情報技術を正しく知っていただき、自らしっかりと活用できるチカラをある程度養っていただくことも重要です。最終的には、これらの技術を自ら楽しんでご活用いただくようになる事が、長期継続的な悩みの解決に繋がるものと考えます。
      </p>
      <p>
      皆様のシステム開発やクラウド導入を行いつつ、お客様ご自身や組織のチカラを向上するお手伝いができればという想いからロングリブネットを立ち上げました。<br/>
      どうぞ長い目でお付き合い頂けますと幸いです。
      </p>
      <p>ロングリブネット<br>長住 直樹（ナガズミ ナオキ）</p>
      <p class="lead_button"><a class="button01" href="#contact">お問い合せ</a></p>
    </div>
  </div>
</section>

<section id="whatsnew">
  <h3 class="underline">What's new</h3>
  <div class="content_block">
    <div class="news">
      <ul>
        {% for news in news_list %}
        <li>
          <p class="wnh">
            <span>{{news.release_day|date:"Y/m/d"}}</span>
            {% if news.category == 'I' %}
            <span class="info"></span>
            {% elif news.category == 'S' %}
            <span class="service"></span>
            {% elif news.category == 'W' %}
            <span class="work"></span>
            {% elif news.category == 'T' %}
            <span class="tech"></span>
            {% else %}
            <span class="other"></span>
            {% endif %}
          </p>
          <p class="wnd"><a href="{% url 'sitebase:newsdetail' news.id %}">{{news.title}}</a></p>
        </li>
        {% endfor %}
      </ul>
      <p class="morenews"><a href="{% url 'sitebase:news' %}">and more ...</a></p>
    </div>
  </div>
</section>

<section id="services">
  <h3 class="underline">Services</h3>
  <div class="services">
    <ul class="container">
      <li class="box">
        <ul>
          <li class="service_title">AWSクラウド導入</li>
          <li class="service_img" style="background-image: url('/static/images/s-service-aws.jpg')"><a href="#services"></a></li>
          <li class="service_comment">代表ナガズミはアマゾンウェブサービスジャパン (AWS) のエンジニアとしての経歴がございます。そのキャリアによる技術知見を元に適切なサポートをご提供いたします。</li>
        </ul>
      </li>
      <li class="box">
        <ul>
          <li class="service_title">ソフトウェア開発</li>
          <li class="service_img" style="background-image: url('/static/images/s-service-system.jpg')"><a href="#services"></a></li>
          <li class="service_comment">お客様のWebアプリケーションなど各種ソフトウェア開発を行います。上流工程から下流工程まで、また、PM や PMO 業務などの開発管理につきましてもお気軽にご相談ください。</li>
        </ul>
      </li>
      <li class="box">
        <ul>
          <li class="service_title">技術顧問</li>
          <li class="service_img" style="background-image: url('/static/images/s-service-advisor.jpg')"><a href="#services"></a></li>
          <li class="service_comment">特に AWS を前提とするシステムアーキテクチャについて、または開発や組織のマネージメント強化、あるいは技術者育成や環境整備といった内容についてご相談いただけます。</li>
        </ul>
      </li>
      <li class="box">
        <ul>
          <li class="service_title">ホームページ作成</li>
          <li class="service_img" style="background-image: url('/static/images/s-service-hp.jpg')"><a href="#services"></a></li>
          <li class="service_comment">PC からスマホまでレスポンシブなデザインのホームページを作成いたします。またチャットなどインタラクティブな Web サイトの開発についてもぜひご相談ください。</li>
        </ul>
      </li>
      <li class="box">
        <ul>
          <li class="service_title">ITエンジニア育成 (サービス準備中)</li>
          <li class="service_img" style="background-image: url('/static/images/s-service-education.jpg')"></li>
          <li class="service_comment">インドや中国出身のグローバルで活躍するエンジニアが増えていますが、我が国出身のエンジニアはまだまだ少ないように思えます。グローバルに活躍できるエンジニアの育成は、ロングリブネットにおける今後の大きなビジョンです。</li>
        </ul>
      </li>
      <li class="box">
        <ul>
          <li class="service_title">大人のIT相談 (サービス準備中)</li>
          <li class="service_img" style="background-image: url('/static/images/s-service-consul.jpg')"></li>
          <li class="service_comment">組織におけるビジネスシステムを設計しているが現構成で大丈夫か不安、新たなシステム責任者となったが協力会社から提案された内容が正しいのか判断つかない、このようなご相談をプロ目線にてお受けします。1時間単位でご相談いただけます。</li>
        </ul>
      </li>
    </ul>
  </div>
</section>

<section id="contact">
  <h3 class="underline">Contact</h3>
  <div class="content_block">
    <div class="pr_eyecatch" style="background-image: url('{% static 'images/contact01.jpg' %}')">
      <h3>ご連絡はこちらまで<br/>お気軽にご相談ください</h3>
    </div>
    <div class="pr_leader">
      <p>
      〒210-0007<BR>
      神奈川県川崎市川崎区駅前本町11番地2 川崎フロンティアビル4階<br>
      ロングリブネット 長住直樹
      </p>
      <p>
      TEL: 050-5241-3096<BR>
      URL: https://www.longlivenet.com/
      </p>
      <p>
      <a class="button01" href="/contact">メールでのお問い合せ（お問い合せフォーム）</a>
      </p>
    </div>
  </div>
</section>

{% endblock %}

sitebase/templates/sitebase/info.html
{% extends "base.html" %}

{% block title %}ご紹介{% endblock title %}

{% block content %}

<section>
  <h1>ナガズミデンサンのご紹介</h1>
  代表ごあいさつ
</section>
<section>
  セクション2
</section>
<section>
  セクション3
</section>

{% endblock %}

sitebase/templates/sitebase/news.html
{% extends "base.html" %}

{% block title %}News{% endblock title %}

{% block content %}

<section id="newslist" class="center_block">
  <h1>NEWS</h1>
  <div class="content_block">
    <div class="news">
      <ul>
        {% for news in page_obj.object_list %}
        <li>
          <p class="wnh">
            <span>{{news.release_day|date:"Y/m/d"}}</span>
            {% if news.category == 'I' %}
            <span class="info"></span>
            {% elif news.category == 'S' %}
            <span class="service"></span>
            {% elif news.category == 'W' %}
            <span class="work"></span>
            {% elif news.category == 'T' %}
            <span class="tech"></span>
            {% else %}
            <span class="other"></span>
            {% endif %}
          </p>
          <p class="wnd">
          <a href="{% url 'sitebase:newsdetail' news.id %}?page={{ page_obj.number }}">{{news.title}}</a>
          </p>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <div class="pagination">
    <span class="step_links">
        {% if page_obj.has_previous %}
          <a href="?page=1" class="button02">&lt;&lt;</a>
          <a href="?page={{ page_obj.previous_page_number }}" class="button02">&lt;</a>
        {% else %}
          <span class="button02_dim">&lt;&lt;</span>
          <span class="button02_dim">&lt;</span>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="button02">&gt;</a>
          <a href="?page={{ page_obj.paginator.num_pages }}" class="button02">&gt;&gt;</a>
        {% else %}
          <span class="button02_dim">&gt;</span>
          <span class="button02_dim">&gt;&gt;</span>
        {% endif %}
    </span>
  </div>
  <div>
    <p class="lead_button">
    <a class="button01" href="/#contact">お問い合せ</a>
    <a class="button01" href="/">ホーム</a>
    </p>
  </div>
</section>

{% endblock %}

sitebase/templates/sitebase/news_detail.html
{% extends "base.html" %}

{% block title %}News{% endblock title %}

{% block content %}

<section id="news_detail" class="center_block">
  <h1>NEWS</h1>
  <h3>{{news.title}}</h3>
  <div class="news_detail">
    {% if news.photo %}
    <p class="news_detail_img"
        style="background-image: url('{{news.photo.url}}')">
    {% endif %}
    <ul>
      <li>発表日: {{news.release_day|date:"Y/m/d"}}</li>
      <li>{{news.content  | linebreaksbr}}</li>
      {% if news.link %}
      <li>詳細はこちら▶︎ <a href="{{news.link}}" target="_blank">{{news.link}}</a></li>
      {% endif %}
    </ul>
    <p class="news_navi">
    {% if page %}
    <a class="button01" href="{% url 'sitebase:news' %}?page={{page}}">NEWS一覧</a>
    {% else %}
    <a class="button01" href="{% url 'sitebase:news' %}">NEWS一覧</a>
    {% endif %}
    <a class="button01" href="/#contact">お問い合せ</a>
    <a class="button01" href="javascript:history.back();">戻る</a>
    </p>
  </div>
</section>

{% endblock %}

sitebase/templates/sitebase/newsdetail.html
{% extends "base.html" %}

{% block title %}News{% endblock title %}

{% block content %}

<section id="news_detail" class="center_block">
  <h1>NEWS</h1>
  <h3>{{news.title}}</h3>
  <div class="news_detail">
    {% if news.photo %}
    <p class="news_detail_img"
        style="background-image: url('{{news.photo.url}}')">
    {% endif %}
    <ul>
      <li>発表日: {{news.release_day|date:"Y/m/d"}}</li>
      <li>{{news.content}}</li>
      {% if news.link %}
      <li>詳細はこちら▶︎ <a href="{{news.link}}" target="_blank">{{news.link}}</a></li>
      {% endif %}
    </ul>
    <p class="news_navi">
    <a class="button01" href="/#contact">お問い合わせ</a>
    {% if page %}
    <a class="button01" href="{% url 'sitebase:news' %}?page={{page}}">NEWS一覧</a>
    {% else %}
    <a class="button01" href="{% url 'sitebase:news' %}">NEWS一覧</a>
    {% endif %}
    <a class="button01" href="/">ホーム</a>
    </p>
  </div>
</section>

{% endblock %}

sitebase/templates/sitebase/privacy.html
{% extends "base.html" %}

{% block title %}Privacy{% endblock title %}

{% block content %}

<section>
  <h1>プライバシー・ポリシー</h1>
  セクション1
</section>
<section>
  セクション2
</section>
<section>
  セクション3
</section>

{% endblock %}

sitebase/templates/sitebase/services.html
{% extends "base.html" %}

{% block title %}サービス{% endblock title %}

{% block content %}

<section>
  <h1>提供サービスのご紹介</h1>
  セクション1
</section>
<section>
  セクション2
</section>
<section>
  セクション3
</section>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>ロングリブネット / {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'base_style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-159250906-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-159250906-1');
    </script>

  </head>
  <body>
    {% include "header.html" %}

    <main>
    {% block content %}
    {% endblock %}
    </main>

    {% include "footer.html" %}
  </body>
</html>

templates/footer.html
<footer>
  <div>
    © 2020 ロングリブネット
  </div>
</footer>

templates/header.html
{% load static %}

<header id="headermenu">
  <p class=title><a href="/">ロングリブネット</a></p>
  <ul>
    <li id="rightmenu_trigger">
      <a href="#"><img src="{% static 'icons/hamberger03.png' %}" alt="MENU"></a>
    </li>
    <li id="rightmenu">
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/#message">Message</a></li>
        <li><a href="/news">News</a></li>
        <li><a href="/#services">Services</a></li>
        <li><a href="/#contact">Contact</a></li>
      </ul>
    </li>
  </ul>
</header>